version: '2'
services:
  dagda:
    build: .
    image: 3grander/dagda:0.8.0
    container_name: dagda
    networks:
      - mdb
    environment: 
      - MONGODB_PORT=27017
      - MONGODB_HOST=vulndb
      - DAGDA_HOST=127.0.0.1
      - DAGDA_PORT=5000
    entrypoint: python dagda.py start -s 0.0.0.0 -p 5000 -m vulndb -mp 27017
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /tmp:/tmp
    depends_on:
      - vulndb
  vulndb:
    image: mongo
    container_name: vulndb
    networks:
      - mdb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
networks:
  mdb:
    external: false